apiVersion: apps/v1
kind: Deployment
metadata:
  name: ob-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ob-web
      owner: onlinebank
  template:
    metadata:
      annotations:
        logcollect: 'true'
      labels:
        app: ob-web
        owner: onlinebank
    spec:
      containers:
        - name: ob-web
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          env:
            - name: REPLACED_FOR_ROLLING_UPDATE
              value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          ports:
            - containerPort: 8080
      terminationGracePeriodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: ob-web-svc
spec:
  selector:
    app: ob-web
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header X-Content-Type-Options "nosniff" always;
  labels:
    app: ob-web
  name: ob-web-ingress
spec:
  rules:
    - host: INGRESS_HOST_IS_REPLACED_DURING_BUILD
      http:
        paths:
          - backend:
              serviceName: ob-web-svc
              servicePort: 80
            path:
              /
              #/onlinebank-public/web
