service:
  replicaCount: 1

  # define spring profiles for service. Internal profile would be added if internal: enabled
  #SPRING_PROFILES_ACTIVE: config-$BUILD_TYPE,metrics,logging,onlinebank-db-$BUILD_TYPE,kafka-$BUILD_TYPE,redis-$BUILD_TYPE,elastic-$BUILD_TYPE,adapter-api-$BUILD_TYPE,i18n-$BUILD_TYPE,neighbour-adapter-api

  # deploy service with public profile.
  public:
    enabled: true

  # deploy service with internal profile.
  internal:
    enabled: false

  image:
    # main image to build services
    repository: $IMAGE_PATH
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: '$VERSION'

  extraEnv:
    {}
    # Specifies your custom environment variables. They would be added to both internal & public deployment
    #- name: My_VAR
    #  value: my_value

  extraLabels:
    version: '$VERSION'
    process/obweb: ''

  # health check probes.
  #probes:
  #  path: /swagger-ui.html
  # Custom probe port. Default is container http port
  # port: metrics

  # container port.
  # please dont use ports under 1024
  httpPort: 8080

  ingress:
    enabled: true
    className: 'public'
    annotations:
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/whitelist-source-range: '10.0.0.0/8'
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: beta.dev.onlinebank.kz
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: star-dev-onlinebank-kz
        hosts:
          - beta.dev.onlinebank.kz

  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 1024Mi
